---
on:
  workflow_call:

permissions: {}

jobs:
  container-scan:
    name: Container Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Clean Actions Runner
        id: clean_actions_runner
        uses: ministryofjustice/analytical-platform-github-actions/clean-actions-runner@36ec5526b1400f4a5d48ad0e5957993e1401cb9f # main
        with:
          confirm: true

      - name: Build
        id: build
        uses: docker/build-push-action@14487ce63c7a62a4a324b0bfb37086795e31c6c1 # v6.16.0
        with:
          context: .
          push: false
          tags: ${{ github.sha }}

      - name: Generate .trivyignore
        id: generate_trivyignore
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          imageName=$(grep "^FROM" Dockerfile | cut -d' ' -f2 | cut -d':' -f1)
          imageVersion=$(grep "^FROM" Dockerfile | cut -d':' -f2 | cut -d'@' -f1)

          if [[ "${imageName}" == "ghcr.io/ministryofjustice/analytical-platform-"* ]]; then
            imageRepository=${imageName#ghcr.io/}

            downloadTrivyignore=$(gh api "repos/${imageRepository}/contents/.trivyignore?ref=${imageVersion}" 2>/dev/null || true)
            export downloadTrivyignore

            downloadTrivyignoreStatus=$(jq -r '.status' <<< "${downloadTrivyignore}")
            export downloadTrivyignoreStatus

            if [[ "${downloadTrivyignoreStatus}" == "null" ]]; then
              echo ".trivyignore found, writing to file"
              jq -r '.content' <<< "${downloadTrivyignore}" | base64 --decode > .base-trivyignore

              if [[ ! -f .trivyignore ]]; then
                echo ".trivyignore not found, creating new file"
                mv .base-trivyignore .trivyignore
              else
                echo ".trivyignore already exists, merging with existing file"
                cat .base-trivyignore >> .trivyignore
              fi

            elif [[ "${downloadTrivyignoreStatus}" == "404" ]]; then
              echo ".trivyignore not found" # It's OK if we don't find one, it means one might not exist
            else
              echo "Error downloading .trivyignore"
              exit 1
            fi
          else
            echo "Image is not an Analytical Platform image, skipping .trivyignore download"
          fi

      - name: Scan
        id: scan
        uses: aquasecurity/trivy-action@6c175e9c4083a92bbca2f9724c8a5e33bc2d97a5 # v0.30.0
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          image-ref: ${{ github.sha }}
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1
