---
name: 🧪 Test clean-actions-runner

on:
  pull_request:
    branches:
      - main
    paths:
      - clean-actions-runner/**

permissions: {}

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run clean-actions-runner
        id: clean_actions_runner
        uses: ./clean-actions-runner
        with:
          confirm: true

  no-confirm:
    name: No Confirm
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Run clean-actions-runner
        id: clean_actions_runner
        uses: ./clean-actions-runner
        continue-on-error: true
        with:
          confirm: false
